# ============================================================================
# Local Values – Lex Bot Configuration & Tagging
# ============================================================================
# Purpose:
# ----------------------------------------------------------------------------
# - Loads bot configuration from bot-config.json
# - Defines derived values used across Terraform resources
# - Centralizes tagging strategy for all AWS resources
#
# Key Components:
# ----------------------------------------------------------------------------
# | Local Name   | Description                                      |
# |--------------|--------------------------------------------------|
# | bot_config   | Parsed JSON configuration for the bot            |
# | bot_name     | Bot name extracted from configuration            |
# | polly_arn    | ARN pattern for Amazon Polly access              |
# | tags         | Standardized tags applied to all resources       |
#
# Notes:
# ----------------------------------------------------------------------------
# - bot-config.json is the primary input for bot behavior (intents, flows)
# - End users should modify bot-config.json instead of Terraform code
# - Tags follow organizational standards for governance and cost tracking
# ============================================================================
# Generated by BotFoundry – Lex Bot Platform Template

locals {
  # Load bot configuration
  bot_config = try(
    jsondecode(file("${path.module}/../bot-config.json")),
    {}
  )

  # Extract bot name from config
  bot_name = local.bot_config.name

  # Polly ARN (used for Lex voice capabilities if needed)
  polly_arn = "arn:aws:polly:${var.aws_region}:${var.aws_account_id}:lexicon/*"

  # Standard tags applied to all resources
  tags = {
    MANAGED_BY       = "Terraform"
    ENVIRONMENT      = var.environment
    AWS_REGION       = var.aws_region
    AWS_ACCOUNT_NAME = var.aws_account_name
    AWS_ACCOUNT_ID   = var.aws_account_id
  }
}